language: node_js

node_js:
  - "8"

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - cargo install wasm-pack

script:
  - npm run build
  - npm run publish
