language: node_js

# cache:
#   directories:
#     - $HOME/.cargo
#     - $TRAVIS_BUILD_DIR/target

node_js:
  - "12"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -y

stages:
  - test
  - name: deploy
    if: (NOT type IN (pull_request)) AND (branch = master)

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: deploy
      script:
        - npm run build
        - npm run publish
