[package]
name = "wa-vs-js-benchmark"
version = "0.1.0"
authors = ["Marco Montalbano <marcomontalbano.work@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
